#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

KAFKA_PACKAGE="org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.3"
EVIDENCE_DIR="outputs/evidence"
API_PID=""
SPARK_SUBMIT_BIN="${SPARK_SUBMIT_BIN:-spark-submit}"
if command -v python3 >/dev/null 2>&1; then
  PYTHON_BIN="${PYTHON_BIN:-python3}"
elif command -v python >/dev/null 2>&1; then
  PYTHON_BIN="${PYTHON_BIN:-python}"
else
  echo "Neither python3 nor python is available." >&2
  exit 1
fi

cleanup() {
  if [[ -n "${API_PID}" ]] && kill -0 "${API_PID}" >/dev/null 2>&1; then
    kill "${API_PID}" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

run_capture() {
  local name="$1"
  shift
  echo ">>> $*" | tee "${EVIDENCE_DIR}/${name}.txt"
  "$@" 2>&1 | tee -a "${EVIDENCE_DIR}/${name}.txt"
}

wait_for_kafka() {
  local attempts=60
  for attempt in $(seq 1 "${attempts}"); do
    if docker exec kafka1 kafka-topics --bootstrap-server kafka1:29092 --list >/dev/null 2>&1; then
      echo "Kafka is ready after ${attempt} attempt(s)."
      return 0
    fi
    sleep 5
  done
  echo "Kafka did not become ready in time." >&2
  return 1
}

rm -rf /tmp/datalake outputs/analytics outputs/evidence
mkdir -p outputs/analytics outputs/evidence
: > outputs/analytics/.gitkeep

run_capture "01_docker_compose_down" docker compose down -v
run_capture "02_docker_compose_up" docker compose up -d
wait_for_kafka 2>&1 | tee "${EVIDENCE_DIR}/03_wait_for_kafka.txt"

run_capture "04_topic_describe_before_failure" \
  docker exec kafka1 kafka-topics --bootstrap-server kafka1:29092 --describe --topic sensor-events

run_capture "05_stop_kafka2" docker stop kafka2
sleep 20

run_capture "06_topic_describe_after_kafka2_stop" \
  docker exec kafka1 kafka-topics --bootstrap-server kafka1:29092 --describe --topic sensor-events

run_capture "07_start_kafka2" docker start kafka2
sleep 25

run_capture "08_topic_describe_after_kafka2_restart" \
  docker exec kafka1 kafka-topics --bootstrap-server kafka1:29092 --describe --topic sensor-events

run_capture "09_producer" \
  "${PYTHON_BIN}" src/producer.py --count 1000 --rate 200 --source site-A-rack-12 --seed 20252208 --demo-time-span-minutes 15

run_capture "10_spark_pipeline" \
  "${SPARK_SUBMIT_BIN}" --packages "${KAFKA_PACKAGE}" src/spark_pipeline.py --duration-seconds 180 --trigger "10 seconds"

run_capture "11_datalake_files" bash -lc "find /tmp/datalake -maxdepth 8 -type f | sort | head -200"

run_capture "12_analytics" "${SPARK_SUBMIT_BIN}" src/analytics.py

"${PYTHON_BIN}" api/app.py > "${EVIDENCE_DIR}/13_flask_api.log" 2>&1 &
API_PID="$!"
sleep 10

run_capture "14_curl_tests" bash tests/test_curl_commands.sh

run_capture "15_check_submission" bash scripts/check_submission.sh

cat > "${EVIDENCE_DIR}/README.txt" <<'EOF'
Evidence generated by scripts/run_full_demo.sh.

Manual screenshots still recommended:
1. Kafka UI at http://localhost:8080 showing the local-kraft cluster and sensor-events topic.
2. Kafka UI consumer group page showing lag after the Spark pipeline has consumed data.
3. Terminal screenshot of tests/test_curl_commands.sh output, if required by the evaluator.
EOF

echo "Full demo finished. Evidence files are in ${EVIDENCE_DIR}/."
